production:
  sessions:
    default:
      database: docker_rails_demo
      hosts:
        - <%= ENV['MONGO_PORT_27017_TCP_ADDR'] || 'localhost' %>:<%= ENV['MONGO_PORT_27017_TCP_PORT'] || '27017' %>
development:
  sessions:
    default:
      database: docker_rails_demo_development
      hosts:
        - 'localhost:27017'
test:
  sessions:
    default:
      database: docker_rails_demo_test
      hosts:
        - 'localhost:27017'
